spring:
  jmx:
    enabled: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.97.124.4:3306/guns??useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: Thc19940301!

javafx:
  title: asuka-generator
  stage:
    resizable: true

# Mybatis配置
mybatis:
  mapperLocations: classpath:mapper/**/*.xml

